// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9WZP8uv1_aCAu0zxTCSyRkU5tJFLXOUc',
    appId: '1:782012103064:web:7c2cfc82481a7ddac813ed',
    messagingSenderId: '782012103064',
    projectId: 'linea-de-profundizacion-51602',
    authDomain: 'linea-de-profundizacion-51602.firebaseapp.com',
    storageBucket: 'linea-de-profundizacion-51602.appspot.com',
    measurementId: 'G-ZJFSRJ0GMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPkJUfSbhWT5ZGjR0HCezvkZEtNBLbzM',
    appId: '1:782012103064:android:be5a396b9536c61ec813ed',
    messagingSenderId: '782012103064',
    projectId: 'linea-de-profundizacion-51602',
    storageBucket: 'linea-de-profundizacion-51602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_AHG7Ubar4QeAtGD8M2t5zEfayDISHY0',
    appId: '1:782012103064:ios:3b5822d5c6604efdc813ed',
    messagingSenderId: '782012103064',
    projectId: 'linea-de-profundizacion-51602',
    storageBucket: 'linea-de-profundizacion-51602.appspot.com',
    iosClientId: '782012103064-p1ujl3vn65k63got2nquvrnjde3u8sdo.apps.googleusercontent.com',
    iosBundleId: 'com.ucundinamarca.primerproyecto',
  );
}
